# Generated by Django 3.2.9 on 2021-12-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20211202_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='payment_date',
        ),
    ]
