# Generated by Django 3.2.9 on 2022-01-03 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_registration_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
