# Generated by Django 3.2.9 on 2022-01-15 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('event', '0004_registration_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.payment'),
        ),
    ]
