services:
    db:
        image: library/postgres:14.1-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./backend/envs/.env.db.dev
#        networks:
#            custom_net:
#                ipv4_address: 127.0.0.2
    
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
#        networks:
#            custom_net:
#                ipv4_address: 127.0.0.1
        volumes:
            - ./backend:/backend/
            - static_volume:/staticfiles
            - media_volume:/media
        ports:
            - 8000:8000
        env_file:
            - ./backend/envs/.env.dev
        depends_on:
            - db
        restart: "on-failure"


#networks:
#    custom_net:
#        driver: bridge
#        ipam:
#            config:
#                - subnet: 127.0.0.4/24

volumes:
    postgres_data:
    static_volume:
    media_volume:
