# Generated by Django 3.2.9 on 2021-12-01 19:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_owner_announcement_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='hide_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 8, 19, 25, 27, 230888, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='announcement',
            name='publish_date',
            field=models.DateField(auto_now=True),
        ),
    ]
