# Generated by Django 3.2.9 on 2021-12-01 19:33

from django.db import migrations, models
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211201_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='hide_date',
            field=models.DateField(default=home.models.now_with_delay),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
