# Generated by Django 3.2.9 on 2021-12-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211201_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
