# Generated by Django 3.2.9 on 2021-12-02 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=3000)),
                ('created', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('hide_date', models.DateField(default=home.models.now_with_delay)),
                ('pinned', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
