# Generated by Django 3.2.9 on 2022-01-19 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_registration_payment'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='event.registration'),
        ),
    ]
