# Generated by Django 3.2.9 on 2022-01-19 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_registration_payment'),
        ('payment', '0002_payment_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='event.registration'),
        ),
    ]
